kind: Service
apiVersion: v1

metadata:
  name: manila-api
  labels:
    system: openstack
    type: api
    component: manila
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.global.metrics_port | quote }}
<<<<<<< HEAD
    prometheus.io/targets: {{ required ".Values.alerts.prometheus" .Values.alerts.prometheus |  quote }}
=======
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
>>>>>>> [Manila-Alerts] Moving alerts to Prom-OS tier
spec:
  selector:
    name: manila-api
  ports:
    - name: manila-api
      port: {{.Values.api_port_internal}}
    - name: metrics
      port: {{ .Values.global.metrics_port }}
