apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubernikus.openstack.region }}-{{ .Values.kubernikus.openstack.projectID }}-nodeport
  namespace: kubernikus
spec:
  type: NodePort
  ports:
  - nodePort: 30666
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: {{ .Values.kubernikus.openstack.region }}-{{ .Values.kubernikus.openstack.projectID }}-apiserver
