apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.kubernikus.openstack.projectID" .Values.kubernikus.openstack.region }}-{{ required ".Values.kubernikus.openstack.projectID" .Values.kubernikus.openstack.projectID }}-etcd-aws
  namespace: {{ .Values.kubernikus.namespace }}
type: Opaque
data:
  bucket-name: {{ required ".Values.backup.bucketName" .Values.backup.bucketName | b64enc}}
  region: {{ required ".Values.backup.region" .Values.backup.region | b64enc }}
  access-key-id: {{ required ".Values.backup.accessKeyId" .Values.backup.accessKeyId | b64enc}}
  secret-access-key: {{ required ".Values.backup.secretAccessKey" .Values.backup.secretAccessKey | b64enc }}
