apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubernikus.openstack.region }}-{{ .Values.kubernikus.openstack.projectID }}-etcd-nodeport
  namespace: kubernikus
spec:
  type: NodePort
  ports:
  - nodePort: 30667
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: {{ .Values.kubernikus.openstack.region }}-{{ .Values.kubernikus.openstack.projectID }}-etcd
