images:
  coredns:
    repository: sapcc/coredns
    tag: 1.6.2
  kubedns:
    repository: sapcc/k8s-dns-kube-dns-amd64
    tag: 1.14.13
  dnsmasq_nanny:
    repository: sapcc/k8s-dns-dnsmasq-nanny-amd64
    tag: 1.14.13
  sidecar:
    repository: sapcc/k8s-dns-sidecar-amd64
    tag: 1.14.13

domain: 
clusterip: 
externalIPs: []

kubedns: 
  enabled: true
 
coredns:
  enabled: false