dependencies:
  - name: blackbox-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.4

  - name: event-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2

  - name: fluent-bit
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.8.0

  - name: kube-state-metrics
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.5.0

  - name: k8s-secrets-certificate-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.0

  - name: ntp-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.2

  - name: oomkill-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2

  - name: prometheus-node-exporter
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.6.0

  - name: prometheus-server
    alias: prometheus-collector
    repository: https://charts.eu-de-2.cloud.sap
    version: 2.2.3

  - name: prometheus-server
    alias: prometheus-frontend
    repository: https://charts.eu-de-2.cloud.sap
    version: 2.2.3

  - name: prometheus-kubernetes-rules
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.6

  - name: prometheus-controlplane-rules
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.4
