dependencies:
  - name: kube-proxy 
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.6.1

  - name: kube-dns
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.0

  - name: kubernikus-rbac
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.2.1